### PR TITLE
Fixed compilation error in SGSparseMatrix unittet in absence of Eigen3

### PR DESCRIPTION
**Pull request by lambday**
Introduced by #2755.

### CODE REVIEW

**Comment by lambday** [comment]
Merging.

**Comment by iglesias** [comment]
I am sorry that I did not detect that when reviewing the pr. Thanks a lot for fixing it, @lambday!

**Comment by lambday** [comment]
@iglesias no problems. These kinds of issues are pretty much impossible to detect from the PR itself :( 
I was trying out my cmake patch and serendipitously detected it while eigen3 was turned off.
