### ISSUE TITLE
Shogun compile with protobuf failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by tklein23** [shogun-toolbox/shogun#2178]
Error messages I get when compiling:

```
./src/shogun/io/protobuf/Chunks.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
./src/shogun/io/protobuf/Chunks.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
./src/shogun/io/protobuf/Chunks.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
```

Hotfix: Removing protobuf headers `libprotobuf-dev`.
