### ISSUE TITLE
Can't compile with Eigen < 3.3.3

### ISSUE THREAD

**Issue by micmn** [shogun-toolbox/shogun#4288]
Stan's perceptron unit test fails to compile with Eigen 3.2.92:
`StanMath/stan/math/rev/mat/fun/Eigen_NumTraits.hpp:297:54: error: wrong number of template arguments (6, should be at least 8)` ([full log](https://gist.github.com/micmn/726006db073949e9751152c318ae79e4))
I guess it's due to the fact that Stan requires Eigen 3.3.3 whereas Shogun's minimum requirements is 3.1.2

**Comment by vigsterkr** [comment]
miju :) since we can bundle eigen and afaik Stan actually has a 3.3.3 bundled eigen, i reckon the best would be just to drop as is the whole system detection of eigen and use Stan's eigen bundled.... @FaroukY
