### ISSUE TITLE
octave interface does not build with octave 4.0.0

### ISSUE THREAD

**Issue by beew** [shogun-toolbox/shogun#2850]
Hi, 
Octave 4.0.0 was release last week. I tried to build shogun 4.0 with Octave modular interface and failed with these errors:

[100%] Built target octave_doxy2swig
[100%] Swig source
/home/bee/Downloads/shogun-4.0.0/src/shogun/lib/SGNDArray.h:116: Warning 367: operator*= ignored
/home/bee/Downloads/shogun-4.0.0/src/shogun/lib/SGNDArray.h:123: Warning 365: operator+= ignored
/home/bee/Downloads/shogun-4.0.0/src/shogun/lib/SGNDArray.h:130: Warning 366: operator-= ignored
Scanning dependencies of target octave_modular
[100%] [100%] Building CXX object src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o
Building CXX object src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/sg_print_functions.cpp.o
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1611:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats) {
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1616:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug) {
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1832:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats)
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1836:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug)
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1850:5: error: ‘DECLARE_OCTAVE_ALLOCATOR’ does not name a type
     DECLARE_OCTAVE_ALLOCATOR;
     ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1853:43: error: expected constructor, destructor, or type conversion before ‘;’ token
   DEFINE_OCTAVE_ALLOCATOR(octave_swig_ref);
                                           ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1910:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats) {
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1915:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug) {
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1921:5: error: ‘DECLARE_OCTAVE_ALLOCATOR’ does not name a type
     DECLARE_OCTAVE_ALLOCATOR;
     ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1924:46: error: expected constructor, destructor, or type conversion before ‘;’ token
   DEFINE_OCTAVE_ALLOCATOR(octave_swig_packed);
                                              ^
src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/build.make:292: recipe for target 'src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o' failed
make[2]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/all' failed
make[1]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

I was able to install shogun octave modular successfully with Octave 3.8.2  with a workaround, see my comment on https://github.com/shogun-toolbox/shogun/issues/1995 but  I think this is something else due to other changes in Octave 4.0.0 
http://www.gnu.org/software/octave/NEWS-4.0.html

OS is Ubuntu 15.04 64 bit. Octave is compiled from source and installed in  /usr/local

Thanks.

**Comment by jaelim** [comment]
I had a similar issue with Octave. When you said Octave 4.0.0, you meant to say package version # for Shogun? Like Shogun 4.0.0? Also, the current version of Octave is 3.8.1.

**Comment by jaelim** [comment]
Can you please describe how you were able to install Octave modular with Octave 3.8.2? I have similar problems with Octave modular and as well as Matlab static. Thanks!

**Comment by beew** [comment]
See my comment on https://github.com/shogun-toolbox/shogun/issues/1995
Basically, octave has removed the config.h file upstream and you need to patch Octave's source with the patch from post 12 here http://savannah.gnu.org/bugs/?41027. 

Download the patch. Download Octave 3.8.2 tarball, extract. Open terminal cd into the extracted folder and run 

patch -p1 < /path/to/patch/you/downloaded

Then just compile Octave as usual. Not sure about Matlab. I have done this on Ubuntu 14.04 and 15.04.

**Comment by jaelim** [comment]
Following your guide, I was able to build the Octave modular!

It's shame that they don't tell you the version of program that worked when they build their package w/ Octave bindings. So when a program gets updated, you don't notice the changes, which make hard for new people to install it.

Can I ask why you are trying to upgrade to Octave 4.0 from 3.8.2? Are there some major bugs in 3.8.2 version that you noticed?

Thanks a lot again for you very helpful reply!

**Comment by beew** [comment]
There is no major bug that I am aware of. But I think this is a new major release so I want to try it out and report problems for example here so that the devs have enough time to work out the problems before most people have migrated. I have several two Ubuntus and  one is still running 3.8.2 so all grounds are covered. :) I

**Comment by beew** [comment]
Hello??

**Comment by lisitsyn** [comment]
@beew it looks like a problem with swig generated code. Could you please post this ```src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o``` file somewhere?

**Comment by beew** [comment]
@lisitsyn 

There is no  src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx. It doesn't build. 

/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1611:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats) {
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1616:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug) {
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1832:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats)
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1836:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug)
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1850:5: error: ‘DECLARE_OCTAVE_ALLOCATOR’ does not name a type
     DECLARE_OCTAVE_ALLOCATOR;
     ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1853:43: error: expected constructor, destructor, or type conversion before ‘;’ token
   DEFINE_OCTAVE_ALLOCATOR(octave_swig_ref);
                                           ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1910:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats) {
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1915:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug) {
                  ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1921:5: error: ‘DECLARE_OCTAVE_ALLOCATOR’ does not name a type
     DECLARE_OCTAVE_ALLOCATOR;
     ^
/home/bee/Downloads/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1924:46: error: expected constructor, destructor, or type conversion before ‘;’ token
   DEFINE_OCTAVE_ALLOCATOR(octave_swig_packed);
                                              ^
src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/build.make:292: recipe for target 'src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o' failed
make[2]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/all' failed
make[1]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kwoodle** [comment]
Also can't compile octave_modular for octave-4.0.0
In file included from /usr/include/c++/5.1.1/memory:81:0,
                 from /usr/local/include/octave-4.0.0/octave/idx-vector.h:33,
                 from /usr/local/include/octave-4.0.0/octave/Array.h:36,
                 from /usr/local/include/octave-4.0.0/octave/boolMatrix.h:27,
                 from /usr/local/include/octave-4.0.0/octave/mx-base.h:32,
                 from /usr/local/include/octave-4.0.0/octave/Matrix.h:30,
                 from /usr/local/include/octave-4.0.0/octave/oct.h:33,
                 from /home/kwoodle/src/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:154:
/usr/include/c++/5.1.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
/home/kwoodle/src/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx: At global scope:
/home/kwoodle/src/shogun-4.0.0/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1864:5: error: ‘DECLARE_OCTAVE_ALLOCATOR’ does not name a type
     DECLARE_OCTAVE_ALLOCATOR;


The first 2000 lines of modshogunOCTAVE_wrap.cxx are 80kB. Is there somewhere I can upload this to?
Thanks

**Comment by beew** [comment]
Hello?? Anyone?

**Comment by beew** [comment]
Anyone looking into this?

**Comment by lisitsyn** [comment]
@beew sorry for quite a slow support on that. This could be a swig issue but I better try to reproduce this locally

**Comment by beew** [comment]
Hi,
Are you able to reproduce it? Thanks.

**Comment by besser82** [comment]
@beew: Try to build using swig-3.0.7…  This should at least fix the build…

**Comment by besser82** [comment]
@beew: Using SWIG >= 3.0.7 and this PR: https://github.com/shogun-toolbox/shogun/pull/2882 should fix all issues regarding builds of octave-bindings.

**Comment by beew** [comment]
Hi,

I have installed swig-3.0.7 in /usr/local

```
SWIG Version 3.0.7

Compiled with g++ [x86_64-unknown-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```
But shogun is looking for swig2.0 apparently, I have swig2.0 in my system. if keep it shogun configure fine, if I remove it

```
CMake Error at /usr/share/cmake-3.0/Modules/FindSWIG.cmake:49 ..

```
and configure failed.

I am trying to compile shogun development. 

So is there a way to choose the version of swig to use. I would like to keep swig2.0 as well since other programs may need it.

**Comment by beew** [comment]
I went ahead and tried to build with swig2.0 and got these errors

```
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1611:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats) {
                  ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1616:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug) {
                  ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1832:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats)
                  ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1836:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug)
                  ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1850:5: error: ‘DECLARE_OCTAVE_ALLOCATOR’ does not name a type
     DECLARE_OCTAVE_ALLOCATOR;
     ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1853:43: error: expected constructor, destructor, or type conversion before ‘;’ token
   DEFINE_OCTAVE_ALLOCATOR(octave_swig_ref);
                                           ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1910:18: error: ‘hid_t’ has not been declared
       save_hdf5 (hid_t loc_id, const char *name, bool save_as_floats) {
                  ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1915:18: error: ‘hid_t’ has not been declared
       load_hdf5 (hid_t loc_id, const char *name, bool have_h5giterate_bug) {
                  ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1921:5: error: ‘DECLARE_OCTAVE_ALLOCATOR’ does not name a type
     DECLARE_OCTAVE_ALLOCATOR;
     ^
/home/bee/Downloads/shogun/build/src/interfaces/octave_modular/modshogunOCTAVE_wrap.cxx:1924:46: error: expected constructor, destructor, or type conversion before ‘;’ token
   DEFINE_OCTAVE_ALLOCATOR(octave_swig_packed);
                                              ^
src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/build.make:292: recipe for target 'src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o' failed
make[2]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/modshogunOCTAVE_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:226: recipe for target 'src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/all' failed
make[1]: *** [src/interfaces/octave_modular/CMakeFiles/octave_modular.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1761:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from /home/bee/Downloads/shogun/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:6362:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
cc1plus: warning: unrecognized command line option "-Wno-c++11-narrowing"
Linking CXX shared module _modshogun.so
CMakeFiles/_python_modular.dir/modshogunPYTHON_wrap.cxx.o: In function `shogun_CSGObject___getstate__(shogun::CSGObject*)':
/home/bee/Downloads/shogun/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:9002: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[100%] Built target _python_modular
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by beew** [comment]
Finally it works! Configured with
```
cmake -DSWIG_EXECUTABLE=/usr/local/bin/swig  -DOctaveModular=ON  ..

```
 the -DSWIG_EXCUTABLE  flag picked the correct version of swig and build went through without error.

Thanks!
