### ISSUE TITLE
Cmake error on Ubuntu 14

### ISSUE THREAD

**Issue by ilovejs** [shogun-toolbox/shogun#3195]
I have thses installed:

sudo apt-get install cmake build-essential swig2.0 python-numpy libeigen3-dev libatlas3-base libblas-dev liblapack-dev ccache gcc g++ python2.7-dev

```
Scanning dependencies of target shogun-static
Linking CXX static library libshogun.a
[ 86%] Built target shogun-static
Scanning dependencies of target balanced_conditional_probability_tree
[ 86%] Building CXX object examples/undocumented/libshogun/CMakeFiles/balanced_conditional_probability_tree.dir/balanced_conditional_probability_tree.cpp.o
Linking CXX executable balanced_conditional_probability_tree
/usr/lib/liblapack.so.3gf: undefined reference to `_gfortran_transfer_character_write@GFORTRAN_1.4'
/usr/lib/liblapack.so.3gf: undefined reference to `_gfortran_transfer_integer_write@GFORTRAN_1.4'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/undocumented/libshogun/balanced_conditional_probability_tree] Error 1
make[1]: *** [examples/undocumented/libshogun/CMakeFiles/balanced_conditional_probability_tree.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ilovejs** [comment]
```
Scanning dependencies of target shogun-static
Linking CXX static library libshogun.a
[ 86%] Built target shogun-static
Scanning dependencies of target balanced_conditional_probability_tree
[ 86%] Building CXX object examples/undocumented/libshogun/CMakeFiles/balanced_conditional_probability_tree.dir/balanced_conditional_probability_tree.cpp.o
Linking CXX executable balanced_conditional_probability_tree
/usr/lib/liblapack.so.3gf: undefined reference to `_gfortran_transfer_character_write@GFORTRAN_1.4'
/usr/lib/liblapack.so.3gf: undefined reference to `_gfortran_transfer_integer_write@GFORTRAN_1.4'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/undocumented/libshogun/balanced_conditional_probability_tree] Error 1
make[1]: *** [examples/undocumented/libshogun/CMakeFiles/balanced_conditional_probability_tree.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by vigsterkr** [comment]
@ilovejs which version are you trying to compile?

**Comment by ilovejs** [comment]
the latest release on github v4.1.0

since ubuntu 14 don't have compiled package. I was trying to compile.

I think there are some problems with that sample:
`examples/undocumented/libshogun/balanced_conditional_probability_tree`

so, is there a way to have shogun core, shogun example binary in separate files ?

**Comment by vigsterkr** [comment]
@ilovejs please clone the git repository and check out the develop branch as that one is confirmed to compile on ubuntu 14.04, see the output of the buildbot:
http://buildbot.shogun-toolbox.org/builders/trusty%20-%20libshogun

**Comment by vigsterkr** [comment]
ppa is available at: https://launchpad.net/~shogun-toolbox/+archive/ubuntu/stable
