### ISSUE TITLE
Shogun 6.1.3 does not compile against the latest Shogun's GPL code.

### ISSUE THREAD

**Issue by geektoni** [shogun-toolbox/shogun#4402]
Currently, trying to compile the 6.1.3 version of Shogun with the GPL code won't work, since the GPL code contains some new features which are not compatible with the 6.1.3 release (see the error below). It is not possible to disable the GPL code either because it will result in a cmake error (this will be fixed by #4400). At the moment, these two problems make impossible to compile the 6.1.3 without touching the code manually.

```
[ 74%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/__/gpl/shogun/classifier/svm/SVMSGD.cpp.o
/home/jenkins/workspace/pull-requests-benchmarks-benchmark/libraries/shogun/src/gpl/shogun/classifier/svm/SVMSGD.cpp: In member function ‘virtual bool shogun::CSVMSGD::train_machine(shogun::CFeatures*)’:
/home/jenkins/workspace/pull-requests-benchmarks-benchmark/libraries/shogun/src/gpl/shogun/classifier/svm/SVMSGD.cpp:74:38: error: ‘binary_labels’ was not declared in this scope
  auto labels = binary_labels(m_labels);
```

Shouldn't we add also "releases" of the shogun-gpl code such that to provide to users a version of the shogun-gpl code that actually works with the 6.1.3?

**Comment by vigsterkr** [comment]
mmm wait, the submodule is being tagged... so in master branch the right commit should be marked from the gpl repo, so in a way it's tagged.. but you are right it would be more clear if we would have a tag.. which we actually should be a do now, as we know the exact commit hash that is for 6.1.3.

btw how do you get this error? :) when you checkout master branch do you do `git submodule update`?

**Comment by geektoni** [comment]
> btw how do you get this error? :) when you checkout master branch do you do `git submodule update`?

This error can be generate by running this script here (taken from mlpack benchmark system): 
[https://github.com/mlpack/benchmarks/blob/af93c85c107e5d26a4b32ff5c454b525e53dd942/libraries/shogun_install.sh](https://github.com/mlpack/benchmarks/blob/af93c85c107e5d26a4b32ff5c454b525e53dd942/libraries/shogun_install.sh) where shogun.tar.gz and shogun-gpl.tar.gz are taken from these links (I cannot use `git submodule update` since the shogun.tar.gz file is not a git repo):
```
shogun.tar.gz:  https://github.com/shogun-toolbox/shogun/archive/shogun_6.1.3.tar.gz
shogun-gpl.tar.gz:  https://github.com/shogun-toolbox/shogun-gpl/archive/master.tar.gz
```
If you need more complete logs just look at this link here [http://ci.mlpack.org/job/pull-requests%20benchmarks%20benchmark/18/console](http://ci.mlpack.org/job/pull-requests%20benchmarks%20benchmark/18/console)

**Comment by vigsterkr** [comment]
ok just pushed a tag: https://github.com/shogun-toolbox/shogun-gpl/archive/v6.1.3.tar.gz this should make things work ;)

**Comment by geektoni** [comment]
Thanks! It is compilable now! :)
