### ISSUE TITLE
Python modular compilation fails on ArchLinux

### ISSUE THREAD

**Issue by qwertzdenek** [shogun-toolbox/shogun#2930]
Hi,
I have following configuration:
GCC 5.2.0
Swig 3.0.7
Python 3.5.0

in the end of *make* I get this:
```bash
[100%] Swig source
/home/haswi/abs/shogun/src/shogun-4.0.0/src/shogun/lib/Hash.h:139: Warning 314: 'in' is a python keyword, renaming to '_in'
/home/haswi/abs/shogun/src/shogun-4.0.0/src/shogun/mathematics/linalg/ratapprox/opfunc/RationalApproximation.h:63: Warning 401: Nothing known about base class 'COperatorFunction< float64_t >'. Ignored.
/home/haswi/abs/shogun/src/shogun-4.0.0/src/shogun/mathematics/linalg/ratapprox/opfunc/RationalApproximation.h:63: Warning 401: Maybe you forgot to instantiate 'COperatorFunction< float64_t >' using %template.
Scanning dependencies of target _python_modular
[100%] Building CXX object src/interfaces/python_modular/CMakeFiles/_python_modular.dir/modshogunPYTHON_wrap.cxx.o
[100%] Building CXX object src/interfaces/python_modular/CMakeFiles/_python_modular.dir/sg_print_functions.cpp.o
In file included from /usr/include/python3.5m/numpy/ndarraytypes.h:1781:0,
                 from /usr/include/python3.5m/numpy/ndarrayobject.h:18,
                 from /usr/include/python3.5m/numpy/arrayobject.h:4,
                 from /home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:6180:
/usr/include/python3.5m/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: too many initializers for ‘PyAsyncMethods’
 };
 ^
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: too many initializers for ‘PyMappingMethods’
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: invalid conversion from ‘PyObject* (*)(PyObject*, PyObject*) {aka _object* (*)(_object*, _object*)}’ to ‘unaryfunc {aka _object* (*)(_object*)}’ [-fpermissive]
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: invalid conversion from ‘PyObject* (*)(PyObject*, PyObject*) {aka _object* (*)(_object*, _object*)}’ to ‘unaryfunc {aka _object* (*)(_object*)}’ [-fpermissive]
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: invalid conversion from ‘binaryfunc {aka _object* (*)(_object*, _object*)}’ to ‘unaryfunc {aka _object* (*)(_object*)}’ [-fpermissive]
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: invalid conversion from ‘lenfunc {aka long int (*)(_object*)}’ to ‘binaryfunc {aka _object* (*)(_object*, _object*)}’ [-fpermissive]
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: invalid conversion from ‘objobjargproc {aka int (*)(_object*, _object*, _object*)}’ to ‘binaryfunc {aka _object* (*)(_object*, _object*)}’ [-fpermissive]
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: invalid conversion from ‘ssizeargfunc {aka _object* (*)(_object*, long int)}’ to ‘objobjargproc {aka int (*)(_object*, _object*, _object*)}’ [-fpermissive]
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: invalid conversion from ‘getbufferproc {aka int (*)(_object*, bufferinfo*, int)}’ to ‘lenfunc {aka long int (*)(_object*)}’ [-fpermissive]
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: invalid conversion from ‘releasebufferproc {aka void (*)(_object*, bufferinfo*)}’ to ‘binaryfunc {aka _object* (*)(_object*, _object*)}’ [-fpermissive]
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: cannot convert ‘PyObject* {aka _object*}’ to ‘getbufferproc {aka int (*)(_object*, bufferinfo*, int)}’ in initialization
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:539923:1: error: cannot convert ‘PyObject* {aka _object*}’ to ‘releasebufferproc {aka void (*)(_object*, bufferinfo*)}’ in initialization
/home/haswi/abs/shogun/src/shogun-4.0.0/build/src/interfaces/python_modular/modshogunPYTHON_wrap.cxx:540171:1: error: too many initializers for ‘PyAsyncMethods’
 };
```

This error is repeated many times on different lines.

I have configured CMake with
cmake -DCMAKE_INSTALL_PREFIX=/usr -DPythonModular=ON

Any ideas? Should I have to downgrade some lower version?

**Comment by iglesias** [comment]
I have never user personally Shogun with Python 3 and Swig 3. Python 2.7 and Swig 2.0 should work, and Python 3 with Swigh 2.0 is building fine in Travis too. This is not a proper solution but if you can afford using those versions it might be the fastest workaround to get it to work.

@vigsterkr, any known issue with Python 3 and Swig 3 together?

**Comment by besser82** [comment]
@iglesias: It's an issue caused by changes in Python 3.5 libs.  SWIG 3.0.7 is a confirmed to work version of SWIG and works fine with Python 2.7.X and Python <= 3.4.X builds.  The Fedora RPMs are built with that since Fedora 22.

@qwertzdenek: Same issue for me on [Fedora Rawhide builds](https://koji.fedoraproject.org/koji/taskinfo?taskID=11927204).  Looking deeper into the issue next week.  Maybe there need to be adjustments on SWIG to be made…

**Comment by besser82** [comment]
Some more research on this issue came up with [another project](https://github.com/Rostlab/relna/issues/10) having this problem with Python 3.5, too…  :/

**Comment by besser82** [comment]
So this seems to be a [known (and fixed in master) issue](https://github.com/swig/swig/issues/539) with SWIG and Python >= 3.5.

**Comment by besser82** [comment]
I re-built Shogun (recent checkout from develop) with a [patched SWIG 3.0.7](https://koji.fedoraproject.org/koji/buildinfo?buildID=703612) with Python 3.5 on Fedora 24 and it works.  =)  So that issue should be gone with 3.0.8-release.  Will come up with a link to the build-logs, when shogun-rebuild on Fedora's Koji is finished.
* * *
I applied the following patches (in that order) to SWIG 3.0.7:

https://github.com/swig/swig/commit/ef001de5240c1e05494e23b933b687f3f266045c
https://github.com/swig/swig/commit/3e9854d308b56488e3bcae69acb4618253b49a94
https://github.com/swig/swig/commit/4e8ea4e853efeca6782e905a75f83a5e704a5fb0
https://github.com/swig/swig/commit/327b59a574c81437f79b168655feff04b12ce56d
https://github.com/swig/swig/commit/c5322a9ecb2b9b13ad6300cf1675192a54f952c1
https://github.com/swig/swig/commit/625a405b8e42f944fdc1a87e36725f03b8817a85

**Comment by qwertzdenek** [comment]
It works! :) thank you!

**Comment by besser82** [comment]
Glad to hear about!  =)

**Comment by besser82** [comment]
besser82's [shogun-4.0.1-0.4.git20150913.d8eb73d.fc24](http://koji.fedoraproject.org/koji/buildinfo?buildID=704166) completed.
