### ISSUE TITLE
Compile time error with latest Eigen (3.3.90)

### ISSUE THREAD

**Issue by gf712** [shogun-toolbox/shogun#4870]
When compiling with the latest Eigen version (3.3.90, which I think has not made it to release yet) I get a compile time error (see below). I am not sure if this is an error in our end or there is a bug in the eigen master branch. Someone needs to have a look. Should be fairly straight forward.
 
```
[64/161] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/gp/MultiLaplaceInferenceMethod.cpp.o
FAILED: src/shogun/CMakeFiles/libshogun.dir/machine/gp/MultiLaplaceInferenceMethod.cpp.o 
ccache /usr/bin/c++   -I../src -Isrc -I../src/gpl -Ibitsery/src/bitsery/include -I/usr/lib/x86_64-linux-gnu/../include -I/home/gf712/anaconda3/include -isystem src/shogun/third_party -isystem /usr/local/include/eigen3 -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated   -O3 -fexpensive-optimizations -frerun-cse-after-loop -fcse-follow-jumps -finline-functions -fschedule-insns2 -fthread-jumps -fforce-addr -fstrength-reduce -funroll-loops -mfpmath=sse -fPIC   -fopenmp -std=c++17 -MD -MT src/shogun/CMakeFiles/libshogun.dir/machine/gp/MultiLaplaceInferenceMethod.cpp.o -MF src/shogun/CMakeFiles/libshogun.dir/machine/gp/MultiLaplaceInferenceMethod.cpp.o.d -o src/shogun/CMakeFiles/libshogun.dir/machine/gp/MultiLaplaceInferenceMethod.cpp.o -c ../src/shogun/machine/gp/MultiLaplaceInferenceMethod.cpp
In file included from /usr/local/include/eigen3/Eigen/Core:152,
                 from /usr/local/include/eigen3/Eigen/Dense:1,
                 from /usr/local/include/eigen3/Eigen/Eigen:1,
                 from ../src/shogun/mathematics/eigen3.h:20,
                 from ../src/shogun/machine/gp/MultiLaplaceInferenceMethod.cpp:44:
/usr/local/include/eigen3/Eigen/src/Core/Dot.h: In instantiation of ‘typename Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType Eigen::MatrixBase<Derived>::dot(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>; Derived = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>; typename Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType = double]’:
../src/shogun/machine/gp/MultiLaplaceInferenceMethod.cpp:92:66:   required from here
/usr/local/include/eigen3/Eigen/src/Core/Dot.h:74:3: error: static assertion failed: YOU_TRIED_CALLING_A_VECTOR_METHOD_ON_A_MATRIX
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/eigen3/Eigen/src/Core/Dot.h:75:3: error: static assertion failed: YOU_TRIED_CALLING_A_VECTOR_METHOD_ON_A_MATRIX
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/eigen3/Eigen/src/Core/Dot.h: In instantiation of ‘typename Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType Eigen::MatrixBase<Derived>::dot(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>; Derived = Eigen::Product<Eigen::Map<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, 0>; typename Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType = double]’:
../src/shogun/machine/gp/MultiLaplaceInferenceMethod.cpp:425:85:   required from here
/usr/local/include/eigen3/Eigen/src/Core/Dot.h:74:3: error: static assertion failed: YOU_TRIED_CALLING_A_VECTOR_METHOD_ON_A_MATRIX
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/eigen3/Eigen/src/Core/Dot.h:75:3: error: static assertion failed: YOU_TRIED_CALLING_A_VECTOR_METHOD_ON_A_MATRIX
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(OtherDerived)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/eigen3/Eigen/src/Core/Dot.h: In instantiation of ‘typename Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType Eigen::MatrixBase<Derived>::dot(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> >; Derived = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>; typename Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>::ReturnType = double]’:
../src/shogun/machine/gp/MultiLaplaceInferenceMethod.cpp:507:58:   required from here
/usr/local/include/eigen3/Eigen/src/Core/Dot.h:74:3: error: static assertion failed: YOU_TRIED_CALLING_A_VECTOR_METHOD_ON_A_MATRIX
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
```

**Comment by eadwu** [comment]
Bisected Eigen and got the offending commit as https://gitlab.com/libeigen/eigen/-/commit/f8bc5cb39e2814d171901e45c1d0ebfeaec49e65. Though I'm not sure whether it's a bug upstream since it seems to fixing something that was wrong originally. Not really used to Eigen/Shogun and it's codebase so not sure how to fix either but dumped the commit in case anyone was picking this up.

**Comment by eadwu** [comment]
Linked issue: https://gitlab.com/libeigen/eigen/-/issues/1664

**Comment by gf712** [comment]
Hmm ok, so I think that either we add a `#ifdef` block checking the Eigen version around the code that is causing issues or we don't allow users to compile with Eigen later than 3.3.7, and then we see if it needs fixing once Eigen has an official release. What do you think @vigsterkr?

**Comment by vigsterkr** [comment]
agree, yeah that’s the only sensible solution atm

**Comment by gf712** [comment]
@eadwu do you want to update CMakeLists.txt to throw an error if the user version is above `3.3.7`? Just grep `FIND_PACKAGE(Eigen3` and you'll see where you need to make the change :)
There is also already some version check going on there, so you'll see how to do this if you don't know how to!

**Comment by vinnik-dmitry07** [comment]
A temporary solution was provided:
https://github.com/shogun-toolbox/shogun/commit/428f1b9fbb4e84dc7f5e7bee18ee60edfaaf70a6

**Comment by theartful** [comment]
Homebrew on MacOS upgraded to Eigen 3.3.8, so I guess we need to address this issue.
https://formulae.brew.sh/formula/eigen

**Comment by yiransii** [comment]
Yes! MacOS is using Eigen 3.3.8 and I cannot build the program. Any workaround? Thanks a lot!

**Comment by cenit** [comment]
any news here?
building shogun with Eigen 3.4 (now released, final version from 3.3.90 cited here), is broken...
I will look for a fix, but any hint would be very appreciated

**Comment by nawazishkhan1-nk** [comment]
Any updates on this?

**Comment by cenit** [comment]
on vcpkg we manually fixed shogun to be compatible with eigen 3.4
